/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ScheduleImport } from './routes/schedule'
import { Route as ReviewsImport } from './routes/reviews'
import { Route as MainImport } from './routes/main'
import { Route as GalleryImport } from './routes/gallery'
import { Route as ContactImport } from './routes/contact'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'

// Create/Update Routes

const ScheduleRoute = ScheduleImport.update({
  path: '/schedule',
  getParentRoute: () => rootRoute,
} as any)

const ReviewsRoute = ReviewsImport.update({
  path: '/reviews',
  getParentRoute: () => rootRoute,
} as any)

const MainRoute = MainImport.update({
  path: '/main',
  getParentRoute: () => rootRoute,
} as any)

const GalleryRoute = GalleryImport.update({
  path: '/gallery',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/gallery': {
      preLoaderRoute: typeof GalleryImport
      parentRoute: typeof rootRoute
    }
    '/main': {
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/reviews': {
      preLoaderRoute: typeof ReviewsImport
      parentRoute: typeof rootRoute
    }
    '/schedule': {
      preLoaderRoute: typeof ScheduleImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([LayoutIndexRoute]),
  ContactRoute,
  GalleryRoute,
  MainRoute,
  ReviewsRoute,
  ScheduleRoute,
])

/* prettier-ignore-end */
